apiVersion: apps/v1
kind: Deployment
metadata:
    name: ledger-alchemy-ui-deployment
    labels:
        app: ledger-alchemy-ui
spec:
    replicas: 2
    selector:
        matchLabels:
            app: ledger-alchemy-ui
    template:
        metadata:
            labels:
                app: ledger-alchemy-ui
        spec:
            containers:
                - name: ledger-alchemy-ui-container
                  image: SJC.ocir.io/<DOCKER_OBJECT_STORAGE_NAMESPACE>/ledger-alchemy-ui-microservice:1.3.0
                  imagePullPolicy: 'Always'
                  ports:
                      - containerPort: 4000
            imagePullSecrets:
                - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
    name: ledger-alchemy-ui-service
spec:
    selector:
        app: ledger-alchemy-ui
    type: ClusterIP
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 4000
